# Generated by Django 5.0.6 on 2024-05-20 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('center', '0001_initial'),
        ('vaccin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='State',
            new_name='Storage',
        ),
    ]
